--- 
version: "3"
services: 
  angular: 
    build: CplayerUI
    container_name: angular-docker
    image: shivaagn/angular-app:v4
    network_mode: host
    ports: 
      - "4200:4200"
    restart: always
  favourites: 
    build: 
      context: favourites/
    image: shivaagn/fav:v4
    network_mode: host
    ports: 
      - "8002:8002"
    restart: always
  recommended: 
    build: 
      context: recommended/
    image: shivaagn/recommended:v4
    network_mode: host
    ports: 
      - "8003:8003"
    restart: always
  user: 
    build: 
      context: user/
    image: shivaagn/user:v4
    network_mode: host
    ports: 
      - "8001:8001"
    restart: always
  userauth: 
    build: 
      context: userauth/
    image: shivaagn/userauth:v4
    network_mode: host
    ports: 
      - "8000:8000"
    restart: always

